### ISSUE TITLE
Proposal: expose the current Component props to the query functions. 

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-component-queries#1]
```
const query = ({ width, height, props }) => ...
```

**Comment by ctrlplusb** [comment]
@slorber what do you think of this proposal?  Seem useful?

I guess my one concern would be reusability of the query functions, since they could essentially become dependant on a certain prop configuration.

**Comment by slorber** [comment]
Hmm that does not seem to be a big deal for me. With Redux we can build reusable selectors, but we often use a custom mapStateToProps for each component, that might use props as well. that looks like the same usecase.

(Redux passes props as 2nd arg of the function, so that it can do some optimizations if it detects the provided function only take a single argument. Maybe you can do some optimizations too but don't know what)

**Comment by ctrlplusb** [comment]
Released in v2.0.0
